services:
  job-hunting-preparer:
    build:
      context: .
      dockerfile: Dockerfile
    image: job-hunting-preparer
    container_name: job-hunting-preparer
    environment:
      - LOG_LEVEL=INFO
    ports:
      - "7860:7860"
    depends_on:
      - pgvector
    restart: always
    develop:
      watch:
        - action: rebuild
          path: ./src
          target: /app
          ignore:
            - /src/__pycache__
        - action: rebuild
          path: poetry.lock
    # volumes:
    #   - ./src:/app/src
    #   - ./src/.env:/app/src/.env
        
    command: ["chainlit", "run", "src/main.py", "--host", "0.0.0.0", "--port", "7860", "-h", "-w"]
    # command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "7860", "--log-config", "log-config.json"]
    # command: ["bash", "-c", "./scripts/start.sh"]
  pgvector:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector
    volumes:
      - ./scripts/create-multiple-psql-databases.sh:/docker-entrypoint-initdb.d/create-multiple-psql-databases.sh
    environment:
      - POSTGRES_MULTIPLE_DATABASES="chat_db","record_manager"
      - POSTGRES_USER=dev_user  # dev only
      - POSTGRES_PASSWORD=1234  # dev only
    ports:
      - "5432:5432"